schema_version = "1.0.0"

id = "opengate"
version = "0.3.4"
name = "OpenGate"
tagline = "Social media render formats made simple"
maintainer = "Dennis Fassbaender & Ryan Guy // support@flipfluids.com"
type = "add-on"

website = "https://github.com/dafassi/Blender-OpenGate"

blender_version_min = "5.1.0"

license = [
    "SPDX:GPL-3.0-or-later",
]

copyright = [
    "2026 Dennis Fassbaender & Ryan Guy",
]

tags = ["Render", "Camera", "Compositing"]

[permissions]
files = "Read and write mask combo assets bundled with the extension"
